//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Depot()
        {
            this.DepotTanks = new HashSet<DepotTank>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public Nullable<int> GeolocationId { get; set; }
        public Nullable<int> DepotTypeId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual DepotType DepotType { get; set; }
        public virtual Geolocation Geolocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DepotTank> DepotTanks { get; set; }
    }
}
