//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DepotTank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DepotTank()
        {
            this.TankFuelLevels = new HashSet<TankFuelLevel>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SensorDeviceId { get; set; }
        public Nullable<int> TankId { get; set; }
    
        public virtual SensorDevice SensorDevice { get; set; }
        public virtual Tank Tank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TankFuelLevel> TankFuelLevels { get; set; }
    }
}
