//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FleetTracking
    {
        public int Id { get; set; }
        public Nullable<int> DriverId { get; set; }
        public Nullable<int> VehicleId { get; set; }
        public Nullable<int> FromGeolocationId { get; set; }
        public Nullable<int> ToGeolocationId { get; set; }
        public Nullable<System.DateTime> DepartueTime { get; set; }
        public Nullable<System.DateTime> ArrivalTime { get; set; }
        public string ETA { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Geolocation Geolocation { get; set; }
        public virtual Geolocation Geolocation1 { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
