//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FLMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankFuelLevel
    {
        public int Id { get; set; }
        public Nullable<int> DepotTankId { get; set; }
        public Nullable<decimal> CurrentVolume { get; set; }
        public System.DateTime DateTimeLogged { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> TankFuelLevelInputBatchId { get; set; }
    
        public virtual DepotTank DepotTank { get; set; }
        public virtual TankFuelLevelInputBatch TankFuelLevelInputBatch { get; set; }
    }
}
